name: gateway

services:
  # Redis
  redis:
    image: redis:alpine3.21
    container_name: redis
    environment:
      TZ: "${TZ}"
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - internal_network

  # Base de datos PostgreSQL
  postgres:
    image: postgres:17.1-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      PGUSER: "${POSTGRES_USER}"
      PGDATABASE: "${POSTGRES_DB}"
      TZ: "${TZ}"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/entrypoint-initdb.d:/docker-entrypoint-initdb.d/
    networks:
      - internal_network

  # Base de datos MongoDB
  mongodb:
    container_name: mongodb
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./docker/mongo/init-scripts:/docker-entrypoint-initdb.d/
    networks:
      - internal_network

volumes:
  redis_data:
    driver: local
  postgres_data:
    driver: local
  mongo_data:
    driver: local

networks:
  internal_network:
    driver: bridge